### PR TITLE
Fix broken Debian 9 build

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request fixes the Debian 9 builds that recently started breaking.

## 💭 Motivation and Context ##

Some [Debian 9](https://github.com/cisagov/ansible-role-docker/actions/runs/391949880) [builds](https://github.com/cisagov/ansible-role-guacamole/runs/1475555772) recently started breaking.  I investigated and found that the failures were due to:
1. The use of `pip` to install [`docker-compose`](https://pypi.org/project/docker-compose/) and [`docker[tls]`](https://pypi.org/project/docker/) Python libraries
2. The dropping of Python 2 support from some Python libraries downstream of  [`docker-compose`](https://pypi.org/project/docker-compose/) and [`docker[tls]`](https://pypi.org/project/docker/)

The simplest solution is to just let the system package manager handle the dependencies.  This also fits with our more recent ideas about `pip` dependency management:
* Let the system package manager manage system Python dependencies
* Use `pyenv` if not using the system Python, and in that case let `pip` manage the Python dependencies

One complication that @mcdonnnj pointed out is that the version of `python-docker` installed from the usual Debian Stretch package repositories is several major versions behind the latest.  Therefore we pull that package from [`stretch-backports`](https://backports.debian.org/) instead.

## 🧪 Testing ##

All molecule tests and pre-commit hooks pass.

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
* [x] Tests have been added and/or modified to cover the changes in this PR.
* [x] All new and existing tests pass.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
This looks great to me! 🥇

**Review by hillaryj — APPROVED** [review]
Thanks for fixing this! 🛠️

**Review by dav3r — APPROVED** [review]
Makes sense- let's do it! 🍓

**Review by hillaryj — APPROVED** [review]
🥇

**Pull request merged**
