### PR TITLE
Fix broken support for Kali Linux

### LINKED ISSUE #25: This role should support Kali Linux
# 🚀 Feature Proposal

This Ansible role should support Kali linux.  It currently does not because of [this code](https://github.com/cisagov/ansible-role-docker/blob/develop/tasks/setup_Debian.yml#L13-L20).

## Motivation

1. We want to use Docker on the Kali instances created for the COOL.
2. The lack of support for Kali is [causing build failures](https://github.com/cisagov/ansible-role-pca-gophish-composition/runs/1179473941#step:7:449) in [cisagov/ansible-role-pca-composition](https://github.com/cisagov/ansible-role-pca-gophish-composition).

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

The most recent release of Ansible (2.10) now correctly identifies Kali Linux as being the Kali distribution of the Debian OS family.  This broke the code in this Ansible role that determines how to install Docker on Kali Linux.  This pull request fixes that and therefore resolves #25.

## 💭 Motivation and Context

In the COOL we install Docker on Kali Linux, so this role must correctly support Kali Linux.

## 🧪 Testing

All pre-commit hooks and molecule tests pass.

## 🚥 Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jsf9k** [comment]
@dav3r, @felddy, @hillaryj, and @mcdonnnj - note that the `regex_replace()` foo to handle Kali Linux is no longer necessary as of Ansible 2.10.  We can start removing it from the repositories where it appears.

**Review by dav3r — APPROVED** [review]
Most excellent! 🐲

**Review by mcdonnnj — APPROVED** [review]
Nice work! Thanks for taking care of yet another breaking thing. I do have one "close the loop" concern. This is relying on a feature of Ansible 2.10, but for example in https://github.com/cisagov/kali-packer/blob/d4043fd352096261bcb205eb7221dc7c64328d5b/requirements.txt#L1 there is no version constraint.

**Comment by jsf9k** [comment]
> Nice work! Thanks for taking care of yet another breaking thing. I do have one "close the loop" concern. This is relying on a feature of Ansible 2.10, but for example in https://github.com/cisagov/kali-packer/blob/d4043fd352096261bcb205eb7221dc7c64328d5b/requirements.txt#L1 there is no version constraint.

Excellent point.  I'd like to pin the version to >=2.10 in cisagov/skeleton-ansible-role instead of in each individual repo.  Are you OK with that?

**Comment by mcdonnnj** [comment]
> 
> 
> > Nice work! Thanks for taking care of yet another breaking thing. I do have one "close the loop" concern. This is relying on a feature of Ansible 2.10, but for example in https://github.com/cisagov/kali-packer/blob/d4043fd352096261bcb205eb7221dc7c64328d5b/requirements.txt#L1 there is no version constraint.
> 
> Excellent point. I'd like to pin the version to >=2.10 in cisagov/skeleton-ansible-role instead of in each individual repo. Are you OK with that?

I am completely OK with that solution.

**Comment by jsf9k** [comment]
> I am completely OK with that solution.

I will merge this PR and immediately create the one for cisagov/skeleton-ansible-role.

**Pull request merged**
